
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Mar 05 12:15:33 CET 2026
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LTE = 28;
  public static final int LBRACKET = 9;
  public static final int CONST = 5;
  public static final int CASE = 44;
  public static final int REM = 30;
  public static final int LPAREN = 12;
  public static final int SEMI = 6;
  public static final int CONTINUE = 16;
  public static final int FOR = 43;
  public static final int MINUS = 34;
  public static final int CHARACTER = 48;
  public static final int RPAREN = 13;
  public static final int AND = 39;
  public static final int LT = 26;
  public static final int OR = 38;
  public static final int BOOL = 47;
  public static final int COMMA = 7;
  public static final int INC = 20;
  public static final int DIV = 32;
  public static final int PLUS = 33;
  public static final int IF = 40;
  public static final int ASSIGN = 8;
  public static final int DOT = 22;
  public static final int EOF = 0;
  public static final int RETURN = 19;
  public static final int RBRACKET = 10;
  public static final int NEW = 37;
  public static final int error = 1;
  public static final int MUL = 31;
  public static final int NUMBER = 46;
  public static final int NEQ = 25;
  public static final int IDENT = 45;
  public static final int BREAK = 15;
  public static final int VOID = 14;
  public static final int EQ = 24;
  public static final int GTE = 29;
  public static final int SWITCH = 42;
  public static final int COLON = 36;
  public static final int ELSE = 41;
  public static final int LBRACE = 3;
  public static final int ENUM = 11;
  public static final int READ = 17;
  public static final int RBRACE = 4;
  public static final int PROG = 2;
  public static final int QUESTION = 35;
  public static final int DEC = 21;
  public static final int GT = 27;
  public static final int PRINT = 18;
  public static final int LENGTH = 23;
}

